### ISSUE TITLE
Doc Build failed

### ISSUE THREAD

**Issue by Kr0nox** [NamelessGroup/namelessbot#71]
After merging of #70 the documentation was not build correctly

**Comment by c0derMo** [comment]
Our entire pipeline is failing, because I renamed files to be capitalized differently, but macOS has a case-insensitive filesystem, so git didnt recognize them... I'll hotfix it on master later today

**Comment by c0derMo** [comment]
Fixed in commit [971b4da](https://github.com/NamelessGroup/namelessbot/commit/971b4da495e3fe0b86a37bb9ced332993fac3eab)
